import mongoose from "mongoose";

const highlightSchema = new mongoose.Schema(
    {
        text: { type: String, required: true },       // selected text
        note: { type: String, default: "" },          // optional user note on highlight
    },
    { timestamps: true }
);

const itemSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
        // ─── Core ───────────────────────────────────────────────────────────────
        url: {
            type: String,
            required: true,
            trim: true,
        },
        type: {
            type: String,
            enum: ["article", "tweet", "image", "youtube", "pdf"],
            required: true,
        },
        title: {
            type: String,
            default: "Untitled",
            trim: true,
        },
        content: {
            type: String,     // scraped text content — used for embedding + search
            default: "",
        },
        thumbnail: {
            type: String,     // image URL or YouTube thumbnail
            default: "",
        },

        // ─── AI ─────────────────────────────────────────────────────────────────
        tags: {
            type: [String],   // auto-generated by LangChain + Gemini
            default: [],
        },
        embedding: {
            type: [Number],   // vector from Gemini embedding model
            default: [],
        },

        // ─── Features ───────────────────────────────────────────────────────────
        highlights: {
            type: [highlightSchema],
            default: [],
        },
        collection: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Collection",
            default: null,
        },

        // ─── Resurfacing ────────────────────────────────────────────────────────
        resurfacedAt: {
            type: Date,
            default: null,    // last time this item was shown as a resurface card
        },
    },
    {
        timestamps: true,   // createdAt, updatedAt auto-added by Mongoose
    }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
itemSchema.index({ tags: 1 });              // fast tag-based graph queries
itemSchema.index({ type: 1 });              // filter by content type
itemSchema.index({ collection: 1 });        // filter by collection
itemSchema.index({ createdAt: -1 });        // sort by newest

const Item = mongoose.model("Item", itemSchema);

export default Item;