import mongoose from "mongoose";

const highlightSchema = new mongoose.Schema(
    {
        text: { type: String, required: true },       // selected text
        note: { type: String, default: "" },          // optional user note on highlight
    },
    { timestamps: true }
);

const itemSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
        // ─── Core ───────────────────────────────────────────────────────────────
        url: {
            type: String,
            required: true,
            trim: true,
        },
        type: {
            type: String,
            enum: ["article", "tweet", "image", "youtube", "pdf"],
            required: true,
        },
        title: {
            type: String,
            default: "Untitled",
            trim: true,
        },
        content: {
            type: String,     // scraped text content — used for embedding + search
            default: "",
        },
        thumbnail: {
            type: String,     // image URL or YouTube thumbnail
            default: "",
        },
        sourceKind: {
            type: String,
            enum: ["url", "upload"],
            default: "url",
        },
        sourceUrl: {
            type: String,
            default: "",
            trim: true,
        },
        sourceFileName: {
            type: String,
            default: "",
            trim: true,
        },
        sourceMimeType: {
            type: String,
            default: "",
            trim: true,
        },
        sourceData: {
            type: Buffer,
            default: null,
            select: false,
        },
        sourceStoragePath: {
            type: String,
            default: "",
            trim: true,
        },
        sourceStatus: {
            type: String,
            enum: ["available", "missing"],
            default: "available",
        },

        // ─── AI ─────────────────────────────────────────────────────────────────
        tags: {
            type: [String],   // auto-generated by LangChain + Gemini
            default: [],
        },
        embedding: {
            type: [Number],   // vector from Gemini embedding model
            default: [],
        },
        status: {
            type: String,
            enum: ["pending", "processing", "ready", "failed"],
            default: "ready",
        },
        processingError: {
            type: String,
            default: null,
        },
        summary: {
            type: String,
            default: "",
            trim: true,
        },
        chunkCount: {
            type: Number,
            default: 0,
            min: 0,
        },
        embeddedAt: {
            type: Date,
            default: null,
        },

        // ─── Features ───────────────────────────────────────────────────────────
        highlights: {
            type: [highlightSchema],
            default: [],
        },
        collection: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Collection",
            default: null,
        },

        // ─── Resurfacing ────────────────────────────────────────────────────────
        resurfacedAt: {
            type: Date,
            default: null,    // last time this item was shown as a resurface card
        },
    },
    {
        timestamps: true,   // createdAt, updatedAt auto-added by Mongoose
    }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
itemSchema.index({ tags: 1 });              // fast tag-based graph queries
itemSchema.index({ type: 1 });              // filter by content type
itemSchema.index({ collection: 1 });        // filter by collection
itemSchema.index({ createdAt: -1 });        // sort by newest
itemSchema.index({ user: 1, status: 1 });   // helpful for future ingestion workflows
itemSchema.index({ user: 1, sourceKind: 1 });

const Item = mongoose.model("Item", itemSchema);

export default Item;
